name: mindbalance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  audio_waveforms: ^1.1.1
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+3
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  intl: ^0.20.1
  path_provider: ^2.1.5
  record: ^5.2.0
  shared_preferences: ^2.3.4
  speech_to_text: ^7.0.0
  tflite_flutter: ^0.11.0
  wav: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/yam.tflite
    - assets/labels.txt
